In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("jobList_results.csv",encoding="utf-8")

In [28]:
def format_salary(row):
    Salary = row["salary"]
    row["salary"]= Salary.replace("â‚¹","").replace("a month","").replace("a year","").replace(",","").replace("From","").replace("Full-time","10000").replace("Part-time +3","10000").replace("Up to","")
    
    if "-" in row["salary"]:
        split = row["salary"].split("-")
        salary_min = split[0]
        salary_max = split[1]
    else:
        salary_min = row["salary"]
        salary_max = row["salary"]
        
    
    # row["old_salary"] = Salary
    row["salary_min"] = salary_min 
    row["salary_max"] = salary_max 
    
       
    if "month" in row["salary"]:
        row["salary_min"] = int(row["salary_min"])*12
        row["salary_max"] = int(row["salary_max"])*12
   
    return row

df_salary = df[df["salary"]!= "None"].fillna("12000") #replacing null values in salary with 12000
df_salary = df_salary.apply(format_salary,axis=1) 
df_salary['avg_salary'] = (df_salary["salary_min"].astype(int) + df_salary["salary_max"].astype(int))/2

In [30]:
df_salary.head(30)

,title,company_name,company_location,url,salary,salary_min,salary_max,avg_salary
0,Sr. Databricks Developer,Labcorp,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
1,Technical Writer,ZPE Systems,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
2,Computer Science - online tutor/expert,Chegg India,Remote in India,https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
3,Automation Testing Engineer,BOEING,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
4,Quality Assurance Engineer (Python Automation),NetApp,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
5,Associate Multi-Skill Software Developer - .Ne...,BOEING,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
6,Versatile Team - Experienced Multi-Skill Softw...,BOEING,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
7,Senior Software Engineer - Display,ARM,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
8,Python Developer Intern,Igsrs,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,7000 - 9000,7000,9000,8000.0
9,Freelance Software Developer,seikor,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,53000 - 90000,53000,90000,71500.0
10,Python Senior Developer,Infosys,"Indore, Madhya Pradesh",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
11,Full Stack Developer-Trainee,Wipro,Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,22000 - 53500,22000,53500,37750.0
12,Python Developer,Infiniticube Services Pvt Ltd,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,15000 - 30000,15000,30000,22500.0
13,Engineering Manager,Capital One,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
14,Python Developer,QuantGrade,"Remote in Noida, Uttar Pradesh",https://in.indeed.com/viewjob?&t=Python+Develo...,300000,300000,300000,300000.0
15,Associate Multi-Skill Software Developer - .Ne...,BOEING,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
16,QA Engineer - Performance Testing,Talent500 Tech (India) Private Limited,"Kochi, Kerala",https://in.indeed.com/viewjob?&t=Python+Develo...,1500000 - 3300000,1500000,3300000,2400000.0
17,Computer Science - online tutor/expert,Chegg India,Remote in India,https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
18,"Senior Manager, Principal Software Engineer - ...",Bristol Myers Squibb,"Hyderabad, Telangana",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
19,Python Developer Intern,Igsrs,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,7000 - 9000,7000,9000,8000.0
20,Freelance Software Developer,seikor,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,53000 - 90000,53000,90000,71500.0
21,Python Senior Developer,Infosys,"Indore, Madhya Pradesh",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
22,Full Stack Developer-Trainee,Wipro,Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,22000 - 53500,22000,53500,37750.0
23,Python Developer,QuantGrade,"Remote in Noida, Uttar Pradesh",https://in.indeed.com/viewjob?&t=Python+Develo...,300000,300000,300000,300000.0
24,Python Developer,Infiniticube Services Pvt Ltd,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,15000 - 30000,15000,30000,22500.0
25,"JavaScript, Python and Linux Developer",Infosys,"Thiruvananthapuram, Kerala",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
26,Junior Python Developer,Wisdomleaf Technologies (P) Limited,India,https://in.indeed.com/viewjob?&t=Python+Develo...,300000 - 400000,300000,400000,350000.0
27,Senior Python Developer,Project 42 Labs,Remote in Remote,https://in.indeed.com/viewjob?&t=Python+Develo...,900000,900000,900000,900000.0
28,DevOps Engineering Database Operations Special...,Bristol Myers Squibb,"Hyderabad, Telangana",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
29,Junior Python Developer,Websodev,"Patna, Bihar",https://in.indeed.com/viewjob?&t=Python+Develo...,13500 - 25000,13500,25000,19250.0

In [31]:
# saving the dataframe into csv file
df_salary.to_csv('cleaned_jobList.csv')

In [32]:
df_salary.head()

,title,company_name,company_location,url,salary,salary_min,salary_max,avg_salary
0,Sr. Databricks Developer,Labcorp,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
1,Technical Writer,ZPE Systems,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
2,Computer Science - online tutor/expert,Chegg India,Remote in India,https://in.indeed.com/viewjob?&t=Python+Develo...,10000,10000,10000,10000.0
3,Automation Testing Engineer,BOEING,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0
4,Quality Assurance Engineer (Python Automation),NetApp,"Bengaluru, Karnataka",https://in.indeed.com/viewjob?&t=Python+Develo...,12000,12000,12000,12000.0